services:
  - type: web
    name: dungeon-crawler
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dungeon_crawler:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9